# Generated by Django 5.0.4 on 2024-04-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_useraccount_employment_type_useraccount_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('employee', 'employee')], default='employee', max_length=20),
        ),
    ]
