# Generated by Django 5.0.4 on 2024-04-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_useraccount_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_type',
        ),
    ]
