# Generated by Django 5.0.4 on 2024-05-25 06:50

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=main.models.PathAndRename('profilePictures')),
        ),
    ]
