# Generated by Django 5.0.4 on 2024-06-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
        migrations.DeleteModel(
            name='UserTokens',
        ),
    ]
