# Generated by Django 5.0.4 on 2024-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_stressquestion_added_by_stressquestion_affect'),
    ]

    operations = [
        migrations.AddField(
            model_name='stressquestion',
            name='type',
            field=models.CharField(default='A', max_length=3),
            preserve_default=False,
        ),
    ]
