# Generated by Django 5.0.4 on 2024-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_stressquestion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stressquestion',
            name='affect',
            field=models.CharField(max_length=3),
        ),
    ]
