# Generated by Django 5.0.4 on 2024-06-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_reportgeneration_downloaded_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_stress',
            name='stress_data',
            field=models.IntegerField(),
        ),
    ]
