# Generated by Django 5.0.4 on 2024-07-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_time_employee_stress_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inhale_duration', models.IntegerField()),
                ('exhale_duration', models.IntegerField()),
                ('hold_duration', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
