# Generated by Django 5.0.4 on 2024-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_breathingprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('audioSrc', models.URLField()),
                ('image', models.URLField()),
                ('color', models.CharField(max_length=8)),
            ],
        ),
    ]
