# Generated by Django 5.0.4 on 2024-07-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breathingprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
