# Generated by Django 5.0.4 on 2024-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_breathingprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_team',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
