# Generated by Django 5.0.4 on 2024-06-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_useraccount_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_admin',
        ),
    ]
