# Generated by Django 5.0.4 on 2024-06-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_employeeteam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeTeam',
            new_name='Employee_Team',
        ),
    ]
