# Generated by Django 5.0.4 on 2024-06-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_employeeteam_employee_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
