# Generated by Django 5.0.4 on 2024-06-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
