# Generated by Django 5.0.4 on 2024-06-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_team_team_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='UserTokens',
        ),
    ]
