# Generated by Django 5.0.4 on 2024-06-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_passwordreset_team_usertokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='UserTokens',
        ),
    ]
